# Generated by Django 4.1.4 on 2023-01-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patient_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="sex",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="M",
                max_length=1,
            ),
        ),
    ]
